### ISSUE TITLE
Off-Topic: Getting non-ES6 Bundles of Fetch Inject

### ISSUE THREAD

**Issue by ghost** [recursionbane/tensorflow-prebuilt-classifier#1]
Sorry for opening this here. I looked on your git profile page but didn't see a contact method and issues are closed on the fork of `fetch-inject`. I wanted to let you know I've updated the build system to make it easier to use and you can get a ES5 bundle of Fetch Inject by doing the following:

`npm i && npm run build && cat dist/fetch-inject.umd.js` for UMD
`npm i && npm run build && cat dist/fetch-inject.js` for vanilla IIFE

**EDIT:** This process is the exact same as before, but the NPM scripts have now been simplified.

The dist bundles are also available both in minified and non-minified version on jsDelivr here:

https://cdn.jsdelivr.net/npm/fetch-inject@latest/dist/ - for edge bundles
https://cdn.jsdelivr.net/npm/fetch-inject@1.7.2/dist/fetch-inject.js for IIFE pinned at `1.7.2`

Cheers.

**Comment by recursionbane** [comment]
I have updated my fetch-inject fork with this information.

**Comment by ghost** [comment]
Cool. Enjoy. If you have any questions or awesome ideas I'm happy to help in any way I can. Cheers.
